name: flutter_google_translate
description: Flutter API for google cloud translation - translate to given language, it can be store data and get result form last time.
version: 0.0.3
homepage: https://github.com/ahyangnb/flutter_google_translate

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  html_unescape: ^2.0.0
  #Get api request header of google.
  google_api_headers: ^4.0.1
  #State management.
  get: ^4.6.6
  #Stora data to local.
  get_storage: 2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
