name: flutter_google_translate
description: Flutter API for google cloud translation - translate to given language, it can be store data and get result form last time.
version: 0.0.7
homepage: https://github.com/ahyangnb/flutter_google_translate

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  html_unescape: ^2.0.0
  #Get api request header of google.
  google_api_headers: ^4.0.1
  #State management.
  get: ^4.6.6
  #Stora data to local.
  get_storage: ^2.0.3
#  flutter_compose_ui_modifiers: ^0.3.9
  #Log print.
  logger: ^1.3.0
  #This plugin allows Flutter apps to discover network connectivity types that can be used.
  connectivity_plus: ^6.0.1
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0
  sqlite3: ^2.4.3
  path_provider: ^2.0.0
  path: ^1.9.0
  # ping the google.
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2

dev_dependencies:
    drift_dev: ^2.18.0
    build_runner: ^2.4.9

flutter:
